name: 'Ember Asset Size'
description: 'Find out how much of a change to your asset size a PR will have'
author: 'Chris Manson'
branding:
  icon: 'bar-chart-2'
  color: 'orange'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  use-pr-artifacts:
    description: 'If production assets have been built in a previous step and downloaded for this step, analyze those instead of re-building'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'index.js'
